#!/bin/sh
USER=yang
HOST=nas
DIR=/volume1/websites/hugo/public   # the directory where your web site files should go

hugo -b http://nas.local:8787/ && rsync -avz --delete public/ ${USER}@${HOST}:${DIR} # this will delete everything on the server that's not in the local public folder 

exit 0
